/* programs.js — full CP2020 + Bartmoss Brainware Blowout software list */
const PROGRAM_DB = [
  {name:"Hammer",cls:"Intrusion",str:4,mu:1,cost:400,note:"2D6 to Data Wall STR. Noisy."},
  {name:"Jackhammer",cls:"Intrusion",str:2,mu:2,cost:360,note:"1D6 to Data Wall STR. Quieter."},
  {name:"Pile Driver",cls:"Intrusion",str:8,mu:4,cost:800,note:"4D6 to Data Wall STR."},
  {name:"Portal",cls:"Intrusion",str:2,mu:6,cost:750,note:"Opens door in Data Wall."},
  {name:"Sledgehammer",cls:"Intrusion",str:6,mu:2,cost:600,note:"3D6 to Data Wall STR."},
  {name:"Termite",cls:"Intrusion",str:1,mu:2,cost:160,note:"1D6 to Data Wall STR."},
  {name:"Worm",cls:"Intrusion",str:2,mu:5,cost:660,note:"Opens Data Wall in 2 turns. Silent."},
  {name:"Dwarf",cls:"Intrusion",str:3,mu:3,cost:230,note:"Strong Worm."},
  {name:"Grubb",cls:"Intrusion",str:1,mu:3,cost:210,note:"Weak Worm."},
  {name:"Japanese Water Torture",cls:"Intrusion",str:3,mu:4,cost:260,note:"2 turns; +1 STR per extra turn, max 7."},
  {name:"Ramming Piston",cls:"Intrusion",str:10,mu:3,cost:900,note:"Ultra-loud Hammer: 5D6 to Wall STR."},
  {name:"Codecracker",cls:"Decryption",str:3,mu:2,cost:380,note:"Opens Code Gates."},
  {name:"Dupre'",cls:"Decryption",str:4,mu:4,cost:900,note:"Opens Code Gates & File Locks."},
  {name:"Raffles",cls:"Decryption",str:5,mu:4,cost:560,note:"Opens Code Gates & File Locks."},
  {name:"Wizard's Book",cls:"Decryption",str:6,mu:2,cost:400,note:"Code gates as STR 6; file locks STR 4."},
  {name:"Cyfermaster",cls:"Decryption",str:6,mu:3,cost:700,note:"Raffles variant."},
  {name:"Tinweasel",cls:"Decryption",str:3,mu:4,cost:300,note:"Sneaky decryptor."},
  {name:"Bloodhound",cls:"Detection",str:3,mu:5,cost:700,note:"Detects entry, traces, alerts master."},
  {name:"Bulldog",cls:"Detection",str:6,mu:6,cost:660,note:"Detects entry, alerts, hangs up on intruder."},
  {name:"Cry Baby",cls:"Detection",str:4,mu:4,cost:430,note:"Tags; +4 to traces when copied."},
  {name:"Clairvoyance",cls:"Detection",str:4,mu:4,cost:720,note:"Detects/identifies ICONs within 2 subgrids."},
  {name:"Guard Dog",cls:"Detection",str:4,mu:5,cost:720,note:"Invisible; detects entry, alerts master."},
  {name:"Hidden Virtue",cls:"Detection",str:3,mu:1,cost:280,note:"Detects real things in VRs."},
  {name:"Looking Glass",cls:"Detection",str:3,mu:3,cost:270,note:"Detects disguised ICONs."},
  {name:"Pit Bull",cls:"Detection",str:2,mu:6,cost:780,note:"Detects, traces, hangs up until destroyed."},
  {name:"SeeYa",cls:"Detection",str:3,mu:1,cost:280,note:"Detects invisible ICONs."},
  {name:"Shadow",cls:"Detection",str:4,mu:3,cost:540,note:"Degrades evasion programs."},
  {name:"Smarteye",cls:"Detection",str:3,mu:4,cost:620,note:"Detects programs in 10 spaces; IDs attack progs."},
  {name:"Speedtrap",cls:"Detection",str:4,mu:4,cost:600,note:"Detects attack programs within 10 spaces."},
  {name:"Watchdog",cls:"Detection",str:4,mu:5,cost:610,note:"Detects entry, alerts owner."},
  {name:"Canis Major",cls:"Detection",str:4,mu:5,cost:610,note:"Watchdog variant."},
  {name:"Data Raven",cls:"Detection",str:5,mu:6,cost:1000,note:"Patient Bloodhound variant."},
  {name:"Fang",cls:"Detection",str:4,mu:6,cost:1300,note:"Pit Bull variant."},
  {name:"Fang 2.0",cls:"Detection",str:5,mu:6,cost:1600,note:"Pit Bull variant."},
  {name:"Fetch 4.01.1",cls:"Detection",str:6,mu:5,cost:700,note:"Bloodhound variant."},
  {name:"Hunter",cls:"Detection",str:5,mu:5,cost:900,note:"Bloodhound variant."},
  {name:"Mouse",cls:"Detection",str:5,mu:5,cost:350,note:"Creeps into fort to look around."},
  {name:"Netspace Inverter",cls:"Detection",str:3,mu:4,cost:540,note:"Recon-drone SeeYa."},
  {name:"Rex",cls:"Detection",str:3,mu:6,cost:1000,note:"Pit Bull variant."},
  {name:"Cascade",cls:"Anti-System",str:7,mu:4,cost:900,note:"Erases 2D6 MU of random memory."},
  {name:"DeckKRASH",cls:"Anti-System",str:4,mu:2,cost:600,note:"Crashes cyberdecks 1D6 turns."},
  {name:"Flatline",cls:"Anti-System",str:3,mu:2,cost:570,note:"Kills cyberdeck interface."},
  {name:"Grid Wave",cls:"Anti-System",str:7,mu:8,cost:20000,note:"Distorts I-G algorithms."},
  {name:"HellBurner",cls:"Anti-System",str:6,mu:5,cost:1000,note:"Destroys target CPU."},
  {name:"Krash",cls:"Anti-System",str:3,mu:2,cost:570,note:"Crashes closest CPU 1D6+1 turns."},
  {name:"Murphy",cls:"Anti-System",str:3,mu:2,cost:600,note:"System randomly activates programs."},
  {name:"Pi in the Face",cls:"Anti-System",str:5,mu:4,cost:800,note:"Makes CPU calculate Pi."},
  {name:"Poison Flatline",cls:"Anti-System",str:2,mu:2,cost:540,note:"Kills system RAM."},
  {name:"Swarm",cls:"Anti-System",str:1,mu:7,cost:3000,note:"System produces more Swarm programs."},
  {name:"Typhoid Mary",cls:"Anti-System",str:6,mu:8,cost:2400,note:"Infiltrates runner, deletes files."},
  {name:"Weed",cls:"Anti-System",str:2,mu:3,cost:630,note:"\u22121 target speed per hit."},
  {name:"Virizz",cls:"Anti-System",str:4,mu:2,cost:600,note:"Ties up 1 system action until destroyed."},
  {name:"Viral 15",cls:"Anti-System",str:4,mu:2,cost:590,note:"Randomly erases one file each turn."},
  {name:"Asp",cls:"Anti-System",str:4,mu:2,cost:800,note:"Flatline variant."},
  {name:"Cascade II",cls:"Anti-System",str:3,mu:2,cost:800,note:"Programs switch on/off at random."},
  {name:"Clown",cls:"Anti-System",str:3,mu:5,cost:1130,note:"Programs \u22121 STR; runners \u22121 Init."},
  {name:"Fragmentation Storm",cls:"Anti-System",str:4,mu:3,cost:1000,note:"Poison Flatline variant."},
  {name:"Poltergeist",cls:"Anti-System",str:5,mu:3,cost:660,note:"Viral 15 variant."},
  {name:"Pox",cls:"Anti-System",str:4,mu:2,cost:800,note:"30% ICE derezzes when activated."},
  {name:"Scatter Shot",cls:"Anti-System",str:4,mu:3,cost:660,note:"Poison Flatline variant."},
  {name:"Vacuum Link",cls:"Anti-System",str:5,mu:3,cost:1200,note:"Relocates runner outside data fort."},
  {name:"Black Mask",cls:"Evasion",str:3,mu:3,cost:200,note:"Disguise ICON as something/someone else."},
  {name:"Domino",cls:"Evasion",str:5,mu:3,cost:1500,note:"ICON looks common to the locale."},
  {name:"George",cls:"Evasion",str:4,mu:1,cost:300,note:"+4 Trace Difficulty."},
  {name:"Invisibility",cls:"Evasion",str:3,mu:1,cost:300,note:"Makes cybersignal invisible."},
  {name:"Replicator",cls:"Evasion",str:3,mu:2,cost:320,note:"Confuses ICE with false signals."},
  {name:"Spore",cls:"Evasion",str:7,mu:7,cost:2320,note:"AI suicide-replication into Net."},
  {name:"Stealth",cls:"Evasion",str:4,mu:3,cost:480,note:"Mutes cybersignal; harder to detect."},
  {name:"Superballs",cls:"Evasion",str:3,mu:4,cost:500,note:"Distracts target: \u22123 initiative."},
  {name:"Cloak (Evasion)",cls:"Evasion",str:5,mu:2,cost:2000,note:"Invisibility variant."},
  {name:"Open-Ended Mileage",cls:"Evasion",str:4,mu:5,cost:330,note:"Routes traces through extended phone link."},
  {name:"Rabbit",cls:"Evasion",str:5,mu:2,cost:360,note:"STR 5 vs Dogs, +2 Speed."},
  {name:"Vewy Vewy Quiet",cls:"Evasion",str:4,mu:2,cost:400,note:"Stealth program."},
  {name:"Armor",cls:"Protection",str:4,mu:2,cost:170,note:"\u22123 vs Stun/Hellbolt/Zombie/Brainwipe/Liche/Hellhound."},
  {name:"DeckShield One",cls:"Protection",str:6,mu:2,cost:320,note:"+3 to deck Data Walls."},
  {name:"Flak",cls:"Protection",str:4,mu:2,cost:180,note:"Static wall blinds attackers; STR 2 vs Dogs."},
  {name:"Force Shield",cls:"Protection",str:4,mu:2,cost:160,note:"Stops attacks against runner."},
  {name:"OutJack",cls:"Protection",str:2,mu:4,cost:150,note:"Jack out if body at Critical."},
  {name:"Reflector",cls:"Protection",str:5,mu:2,cost:160,note:"Reflects Stun/Hellbolt/Knockout."},
  {name:"Shield",cls:"Protection",str:3,mu:1,cost:150,note:"Stops next attack vs runner."},
  {name:"Joan of Arc",cls:"Protection",str:3,mu:2,cost:190,note:"Absorbs anti-personnel damage."},
  {name:"Aardvark",cls:"Anti-IC",str:4,mu:3,cost:1000,note:"Detects and destroys Worms."},
  {name:"Bunnies",cls:"Anti-IC",str:4,mu:3,cost:440,note:"Overloads Vampyres."},
  {name:"Chameleon",cls:"Anti-IC",str:4,mu:6,cost:1650,note:"Killer IV with active Disguise."},
  {name:"Dogcatcher",cls:"Anti-IC",str:10,mu:7,cost:1176,note:"Chases and destroys tracing Dogs."},
  {name:"Dragon",cls:"Anti-IC",str:4,mu:3,cost:960,note:"Attacks and de-rezzes Demons."},
  {name:"Eradicator",cls:"Anti-IC",str:8,mu:7,cost:1600,note:"Killer V; destroys AI spores."},
  {name:"Exorcist",cls:"Anti-IC",str:4,mu:3,cost:600,note:"Removes Possession effects."},
  {name:"Hydra",cls:"Anti-IC",str:3,mu:3,cost:920,note:"Attacks and de-rezzes Demons."},
  {name:"Killer II",cls:"Anti-IC",str:2,mu:5,cost:1320,note:"1D6 to any program STR."},
  {name:"Killer IV",cls:"Anti-IC",str:4,mu:5,cost:1400,note:"1D6 to any program STR."},
  {name:"Killer VI",cls:"Anti-IC",str:6,mu:5,cost:1480,note:"1D6 to any program STR."},
  {name:"Manticore",cls:"Anti-IC",str:2,mu:3,cost:880,note:"Instant de-rezz vs Demon-class."},
  {name:"Mirror",cls:"Anti-IC",str:5,mu:4,cost:1200,note:"Rebounds Hellbolts."},
  {name:"Ninja",cls:"Anti-IC",str:5,mu:5,cost:1520,note:"Invisible Killer."},
  {name:"Possessor",cls:"Anti-IC",str:4,mu:3,cost:1000,note:"Possesses programs."},
  {name:"Raven",cls:"Anti-IC",str:5,mu:4,cost:1000,note:"Blinds any program."},
  {name:"Wolf",cls:"Anti-IC",str:4,mu:6,cost:1500,note:"Killer disguised as Watchdog."},
  {name:"Banpei",cls:"Anti-IC",str:1,mu:5,cost:1280,note:"Killer, 1D6 damage."},
  {name:"Black Dahlia",cls:"Anti-IC",str:7,mu:7,cost:2000,note:"Sexy Killer; 2D6 damage."},
  {name:"Codeslinger",cls:"Anti-IC",str:3,mu:3,cost:1000,note:"Killer, 1D6 damage."},
  {name:"D'Arc Knight",cls:"Anti-IC",str:3,mu:5,cost:1360,note:"Killer, 1D6 damage."},
  {name:"Data Naga",cls:"Anti-IC",str:6,mu:5,cost:1480,note:"Killer, 1D6 damage."},
  {name:"Dropp",cls:"Anti-IC",str:4,mu:4,cost:800,note:"Anti-personnel defense; then jack-out."},
  {name:"Ice Pick Willie",cls:"Anti-IC",str:2,mu:5,cost:1320,note:"Killer, 1D6."},
  {name:"Looney Goon",cls:"Anti-IC",str:2,mu:3,cost:600,note:"Killer, 1D6."},
  {name:"Raptor",cls:"Anti-IC",str:2,mu:4,cost:1200,note:"Killer, 1D6."},
  {name:"Sentinels Prime",cls:"Anti-IC",str:5,mu:5,cost:1440,note:"Killer, 1D6."},
  {name:"Shaka",cls:"Anti-IC",str:2,mu:5,cost:1320,note:"Killer IV variant."},
  {name:"Snowball",cls:"Anti-IC",str:2,mu:5,cost:3000,note:"Grows +2 STR each kill."},
  {name:"Startup Immolator",cls:"Anti-IC",str:4,mu:5,cost:1280,note:"Destroys target if just rezzed."},
  {name:"Triggerman",cls:"Anti-IC",str:4,mu:5,cost:1400,note:"Killer, 1D6."},
  {name:"Wild Card",cls:"Anti-IC",str:1,mu:3,cost:920,note:"Killer, 1D6."},
  {name:"AI Boon",cls:"Anti-IC",str:4,mu:7,cost:3600,note:"1D6 walls/progs; decrypts gates."},
  {name:"Blink",cls:"Anti-IC",str:5,mu:7,cost:1500,note:"1D6 walls/progs; may crash."},
  {name:"Bartmoss Memorial ICEbreaker",cls:"Anti-IC",str:4,mu:2,cost:1500,note:"Compiles 4 anti-prog/intrusion/decrypt progs."},
  {name:"Ball and Chain",cls:"Anti-Personnel",str:3,mu:3,cost:5000,note:"Movement 1 square for 1D6+3 turns."},
  {name:"Brainwipe",cls:"Anti-Personnel",str:3,mu:4,cost:6500,note:"1D6 INT damage per hit; can fry interface."},
  {name:"Cerebus",cls:"Anti-Personnel",str:6,mu:8,cost:9500,note:"Pit Bull that shoots Hellbolts."},
  {name:"Fatal Attractor",cls:"Anti-Personnel",str:7,mu:7,cost:10750,note:"Disguised Hellhound."},
  {name:"Firestarter",cls:"Anti-Personnel",str:4,mu:4,cost:6250,note:"Power surge electrocutes runner."},
  {name:"Glue",cls:"Anti-Personnel",str:5,mu:4,cost:6500,note:"Locks runner 1D10 turns."},
  {name:"Hellbolt",cls:"Anti-Personnel",str:4,mu:4,cost:6750,note:"1D10 physical damage."},
  {name:"Hellhound",cls:"Anti-Personnel",str:6,mu:6,cost:10000,note:"Tracks; heart attack on jackout."},
  {name:"Jack Attack",cls:"Anti-Personnel",str:3,mu:3,cost:6000,note:"Cannot log off 1D6 turns."},
  {name:"King Trail",cls:"Anti-Personnel",str:3,mu:2,cost:3500,note:"Glowing trail 3D6 turns."},
  {name:"Knockout",cls:"Anti-Personnel",str:4,mu:3,cost:6250,note:"Coma 1D6 hours."},
  {name:"Liche",cls:"Anti-Personnel",str:4,mu:4,cost:7250,note:"1D6 INT; erases/overwrites save engrams with pseudo-personality."},
  {name:"Pepe Le Pue",cls:"Anti-Personnel",str:6,mu:5,cost:7750,note:"\u2212INT/REF for 1D6+1 turns."},
  {name:"Psychodrome",cls:"Anti-Personnel",str:4,mu:11,cost:14000,note:"Unconscious 1D6 hours + scare."},
  {name:"Red-Out",cls:"Anti-Personnel",str:5,mu:4,cost:6750,note:"Paralyzes 1D6 turns."},
  {name:"Spazz",cls:"Anti-Personnel",str:4,mu:3,cost:6250,note:"Halves REF 1D6 turns."},
  {name:"Stationery",cls:"Anti-Personnel",str:4,mu:6,cost:10000,note:"Cannot move 5 turns."},
  {name:"Stun",cls:"Anti-Personnel",str:3,mu:3,cost:6000,note:"Freezes 1D6 turns."},
  {name:"Sword",cls:"Anti-Personnel",str:3,mu:4,cost:6250,note:"1D6 physical damage."},
  {name:"The Audio Virus",cls:"Anti-Personnel",str:5,mu:5,cost:8000,note:"\u2212INT/REF until nuked."},
  {name:"Threat",cls:"Anti-Personnel",str:5,mu:6,cost:7000,note:"Forces nervous jack-out."},
  {name:"Werewolf",cls:"Anti-Personnel",str:6,mu:6,cost:13000,note:"Invisible Hellhound variant."},
  {name:"Zombie",cls:"Anti-Personnel",str:5,mu:4,cost:7500,note:"1D6 INT damage; leaves runner mindless if INT reaches 0."},
  {name:"Bolter Cluster",cls:"Anti-Personnel",str:4,mu:4,cost:8000,note:"4D6 damage to runner."},
  {name:"Cinderella",cls:"Anti-Personnel",str:6,mu:4,cost:9000,note:"Firestarter variant."},
  {name:"Code Corpse",cls:"Anti-Personnel",str:5,mu:4,cost:7500,note:"Zombie variant: 1D6 INT damage."},
  {name:"Cortical Scrub",cls:"Anti-Personnel",str:3,mu:4,cost:6500,note:"Brainwipe variant: 1D6 INT damage."},
  {name:"Data Darts",cls:"Anti-Personnel",str:4,mu:4,cost:5500,note:"3D6 damage."},
  {name:"Homewrecker",cls:"Anti-Personnel",str:5,mu:4,cost:8000,note:"Firestarter variant."},
  {name:"Mastiff",cls:"Anti-Personnel",str:5,mu:6,cost:12000,note:"Hellhound variant."},
  {name:"Neural Blade",cls:"Anti-Personnel",str:3,mu:4,cost:6250,note:"Sword variant."},
  {name:"Shockr",cls:"Anti-Personnel",str:3,mu:5,cost:6000,note:"Stun variant."},
  {name:"TKO 2.0",cls:"Anti-Personnel",str:4,mu:3,cost:6250,note:"Knockout variant."},
  {name:"Crystal Ball",cls:"Utility",str:4,mu:1,cost:140,note:"Operates cameras, sensors."},
  {name:"Dee-2",cls:"Utility",str:3,mu:1,cost:130,note:"Operates robotics."},
  {name:"Genie",cls:"Utility",str:5,mu:1,cost:150,note:"Operates doors, elevators."},
  {name:"Hotwire",cls:"Utility",str:3,mu:1,cost:130,note:"Operates remote vehicles."},
  {name:"Knewil",cls:"Utility",str:4,mu:3,cost:220,note:"Remote vehicles on its own."},
  {name:"News At 8",cls:"Utility",str:4,mu:1,cost:140,note:"Data terms / screamsheets via Net."},
  {name:"Open Sesame",cls:"Utility",str:3,mu:1,cost:130,note:"Weaker door/elevator control."},
  {name:"Phone Home",cls:"Utility",str:5,mu:1,cost:150,note:"Place/receive calls in Net."},
  {name:"Rockerbit",cls:"Utility",str:4,mu:2,cost:200,note:"Mikes/voxboxes autonomous."},
  {name:"Soundmachine",cls:"Utility",str:4,mu:1,cost:140,note:"Controls mikes, speakers."},
  {name:"Terminator",cls:"Utility",str:4,mu:2,cost:260,note:"Control terminals."},
  {name:"Viddy Master",cls:"Utility",str:4,mu:1,cost:140,note:"Videoboards etc."},
  {name:"Alias",cls:"Utility",str:6,mu:2,cost:160,note:"Replaces file names."},
  {name:"Backup",cls:"Utility",str:4,mu:1,cost:140,note:"Copy programs."},
  {name:"Breadcrumbs",cls:"Utility",str:4,mu:4,cost:290,note:"Finds new LDL routes."},
  {name:"Cartographer",cls:"Utility",str:6,mu:3,cost:200,note:"Maps data forts."},
  {name:"Databaser",cls:"Utility",str:8,mu:2,cost:180,note:"Opens files to store info."},
  {name:"ElectroLock",cls:"Utility",str:7,mu:2,cost:170,note:"Locks files to File Lock 3."},
  {name:"Filelocker",cls:"Utility",str:4,mu:1,cost:140,note:"Locks files to Code Gate 5."},
  {name:"File Packer",cls:"Utility",str:4,mu:1,cost:140,note:"Packs files to 1/2 size."},
  {name:"Flare Gun",cls:"Utility",str:2,mu:2,cost:300,note:"Net distress signal."},
  {name:"GateMaster",cls:"Utility",str:5,mu:1,cost:150,note:"Anti-virus."},
  {name:"Guest Book",cls:"Utility",str:4,mu:2,cost:200,note:"Area observation."},
  {name:"Instant Replay",cls:"Utility",str:8,mu:2,cost:180,note:"Records runner's trip."},
  {name:"Multinetter",cls:"Utility",str:10,mu:20,cost:2000,note:"Multiple runners one computer."},
  {name:"NetMap",cls:"Utility",str:4,mu:1,cost:150,note:"Major region locator map."},
  {name:"Padlock",cls:"Utility",str:4,mu:2,cost:160,note:"Codeword to log onto deck."},
  {name:"Re-Rezz",cls:"Utility",str:3,mu:1,cost:130,note:"Restores destroyed progs/files."},
  {name:"Translator 2000",cls:"Utility",str:4,mu:2,cost:240,note:"Pictures \u2192 virtual objects."},
  {name:"Imp",cls:"Demon",str:3,mu:3,cost:1000,note:"Demon shell \u2014 carries 2 programs."},
  {name:"Afreet",cls:"Demon",str:3,mu:4,cost:1160,note:"Demon shell \u2014 carries 3 programs."},
  {name:"Succubus",cls:"Demon",str:4,mu:4,cost:1200,note:"Demon shell \u2014 carries 4 programs."},
  {name:"Balron",cls:"Demon",str:5,mu:5,cost:1240,note:"Demon shell \u2014 carries 4 programs."},
  {name:"Thug",cls:"Demon",str:3,mu:6,cost:10440,note:"Permanent 1D6 to prog STR & runners."},
  {name:"Vampyre",cls:"Demon",str:6,mu:7,cost:2300,note:"Can absorb up to 6 programs."},
  {name:"A Picture's Worth",cls:"Multi",str:2,mu:6,cost:1200,note:"Hides data within VRs."},
  {name:"Black Sky",cls:"Multi",str:5,mu:8,cost:4480,note:"Cloud that attacks with lightning."},
  {name:"Dummy",cls:"Multi",str:1,mu:2,cost:450,note:"Fake, disguisable program."},
  {name:"Evil Twin",cls:"Multi",str:8,mu:7,cost:2700,note:"Combination shield/krash."},
  {name:"IGOR",cls:"Multi",str:4,mu:7,cost:4800,note:"On-line flunky."},
  {name:"Lightning Bug",cls:"Multi",str:2,mu:6,cost:1540,note:"6 bugs sally forth vs ICE."},
  {name:"Omnivore",cls:"Multi",str:3,mu:8,cost:18500,note:"Derezz progs, fry CPU, \u22122D6 INT temp."},
  {name:"Scribe",cls:"Multi",str:6,mu:8,cost:0,note:"Stops and disassembles progs for copying."},
  {name:"Wolfpack",cls:"Multi",str:6,mu:8,cost:15200,note:"1D6 prog/Demon; 1D10 to runners."},

  {name:'Lord of the Flies',cls:'Demon',str:8,mu:7,note:'INTERNAL · Recognition; Movement; Conversational; Auto Re-Rezz; Speed; Self-Modifying; Endurance; Code Optimization; Memory · unobtainable by runners',_internal:true,_unobtainable:true},
];
window.PROGRAM_DB = PROGRAM_DB;
